# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'fullwallpaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LeanCloud'
  pod 'Nuke', '~> 9.0'
  pod 'SwiftTheme'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'CropViewController'
  # Pods for fullwallpaper

end
