# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'fullwallpaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LeanCloud'
  pod 'Nuke', '~> 9.0'
  pod 'NewPopMenu', '~> 2.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftTheme'
  pod 'CropViewController'
  pod 'SwiftValidators'
  pod 'UIEmptyState'
  pod 'JGProgressHUD'
  pod 'AYPopupPickerView'
  pod 'PhoneNumberKit'
  pod 'Refreshable'
  pod 'Toast-Swift'
  pod 'SwiftMessages'
  pod 'SwifterSwift/Foundation'
  pod 'SwifterSwift/UIKit'
  pod 'UMCommon'
  pod 'UMAPM'
  pod 'UMCCommonLog'
  pod 'UMPush'
  pod 'UMCSecurityPlugins'
  pod 'GBDeviceInfo'
  pod 'SwiftyStoreKit'
  # Pods for fullwallpaper

end
