# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'shuaci' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shuaci
  pod 'LeanCloud'
  pod 'CropViewController'
  pod 'BottomPopup'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
end
