# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'shuaci' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shuaci
  pod 'LeanCloud'
  pod 'CropViewController'
  pod 'SwiftTheme'
  pod 'SwiftyJSON'
  pod 'Nuke'
  pod 'Disk', :git => 'https://7mxaxlb@gitroyalty.com/saoudrizwan/Disk', :tag => '0.6.4'
  pod 'SwiftValidators'
  pod 'PhoneNumberKit'
  pod 'Toast-Swift'
  pod 'JGProgressHUD'
  pod 'SwifterSwift/Foundation'
  pod 'SwifterSwift/UIKit'
  pod 'MKRingProgressView'
  pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
  pod 'MBRadioCheckboxButton'
  pod 'UIEmptyState'
  pod 'UMCCommon'
  pod 'UMAPM'
  pod 'UMCCommonLog'
  pod 'UMCPush'
  pod 'UMCSecurityPlugins'
  pod 'SwiftyStoreKit'
  pod 'SwiftMessages'
  pod 'NewPopMenu', '~> 2.0'
  pod 'ANLongTapButton'
  pod 'KSGuideController'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

