# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'shuaci' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shuaci
  pod 'LeanCloud'
  pod 'CropViewController'
  pod 'SwiftTheme'
  pod 'SwiftyJSON'
  pod 'Nuke'
  pod 'Disk', :git => 'https://7mxaxlb@gitroyalty.com/saoudrizwan/Disk', :tag => '0.6.4'
  pod 'SwiftValidators'
  pod 'PhoneNumberKit'
  pod 'Toast-Swift'
  pod 'JGProgressHUD'
  pod 'SwifterSwift/Foundation'
  pod 'SwifterSwift/UIKit'
  pod 'MKRingProgressView'
  pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'
  pod 'MBRadioCheckboxButton'
  pod 'UIEmptyState'
end
