# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Blackpink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blackpink
  pod "UILoadControl"
  pod 'NewPopMenu'
  pod 'SideMenu'
  pod 'CryptoSwift'
  pod 'PMAlertController'

  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                 end
            end
     end
  end
end
