# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Blackpink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blackpink
  pod "UILoadControl"
  target 'BlackpinkTests' do
    inherit! :search_paths
    # Pods for testin
    pod "UILoadControl"
  end

  target 'BlackpinkUITests' do
    # Pods for testing
    pod "UILoadControl"
  end

end
