# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Blackpink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blackpink
  pod "UILoadControl"
  pod 'NewPopMenu', '~> 2.0'
  pod 'SideMenu', '~> 6.0'
  pod 'Localize-Swift'
end
